services:
  nginx-proxy:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/default.conf:/tmp/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/start.sh:/tmp/start.sh
    environment:
      - FLASK_SERVER_ADDR=flask-app:8000
    ports:
      - "80:80"
    depends_on:
      - flask-app
    command: bash /tmp/start.sh
  flask-app:
    build:
      context: flask
      dockerfile: ./Dockerfile
    restart: always
    environment:
      - FLASK_SERVER_PORT=8000
    ports:
      - '8000:8000'
    command: gunicorn -w 3 -t 60 -b 0.0.0.0:8000 app:app
